
# Составление фондового индекса

Загрузите данные close_prices.csv. В этом файле приведены цены акций 30 компаний на закрытии торгов за каждый день периода.

In [67]:
import pandas as pd
import sklearn
from sklearn.decomposition import PCA 
import numpy as np

In [68]:
data = pd.read_csv('close_prices.csv')

In [69]:
data.head()

date        AXP          BA        CAT       CSCO         CVX  \
0  2013-09-23  76.440002  117.510002  85.029999  24.270000  125.519997   
1  2013-09-24  76.070000  119.000000  85.110001  24.139999  124.489998   
2  2013-09-25  75.989998  118.510002  84.500000  24.430000  124.070000   
3  2013-09-26  76.320000  119.379997  84.199997  23.770000  123.489998   
4  2013-09-27  75.889999  118.739998  83.800003  23.330000  122.639999   

          DD        DIS         GE          GS  ...        PFE         PG  \
0  59.409999  64.750000  24.280001  165.250000  ...  28.799999  79.279999   
1  59.319997  64.320000  24.320000  162.970001  ...  28.709999  78.620003   
2  59.319997  64.449997  24.230000  162.309998  ...  28.490000  77.720001   
3  59.509996  65.239998  24.250000  162.289993  ...  28.520000  78.050003   
4  59.009995  65.190002  24.049999  159.850006  ...  28.879999  77.209999   

           T        TRV        UNH         UTX           V         VZ  \
0  34.220001  86.379997  71.820000  109.419998  196.240005  47.980000   
1  34.090000  85.870003  72.320000  110.000000  193.339996  47.270000   
2  34.049999  85.980003  71.980003  109.260002  191.559998  46.950001   
3  34.230000  85.830002  72.160004  109.660004  193.559998  47.669998   
4  33.980000  85.410004  71.989998  109.360001  193.050003  47.000000   

         WMT        XOM  
0  76.419998  87.750000  
1  75.750000  87.360001  
2  74.650002  87.139999  
3  74.620003  87.070000  
4  74.360001  86.900002  

[5 rows x 31 columns]

На загруженных данных обучите преобразование PCA с числом компоненты равным 10. Скольких компонент хватит, чтобы объяснить 90% дисперсии?

In [70]:
X_train = data.drop(['date'], axis=1)

In [71]:
pca = PCA(n_components=10)
res = pca.fit(X_train)

In [72]:
#поле explained_variance_ratio_ содержит процент дисперсии,
#который объясняет каждая компонента
variance = res.explained_variance_ratio_
variance

array([0.73897118, 0.11007169, 0.04995088, 0.0287492 , 0.02215448,
       0.01931577, 0.00674853, 0.00614091, 0.00320594, 0.00305611])

In [73]:
#Поле components_ содержит информацию о том, 
#какой вклад вносят признаки в компоненты
comps = res.components_
comps

array([[ 1.61383840e-02,  1.20644923e-01, -5.16612711e-02,
         5.04842369e-02, -1.25859933e-01,  1.14089567e-01,
         2.33906290e-01, -6.20513749e-03,  2.51227032e-01,
         2.88996029e-01, -2.64998795e-01,  9.31320168e-02,
         9.13948403e-02,  4.69879340e-02,  2.90549417e-02,
        -2.61068828e-02,  3.29615584e-01,  7.13897133e-02,
         7.62295699e-02,  2.11888868e-01,  2.30922941e-02,
         7.77316954e-02, -7.20594590e-03,  1.89479745e-01,
         3.21564017e-01,  5.36834873e-02,  5.79683946e-01,
         1.09122230e-04,  8.71614334e-02, -4.29421420e-02],
       [-2.33025791e-01,  1.38102207e-01, -5.64736227e-01,
        -2.94213771e-02, -2.97156167e-01, -7.00723638e-02,
        -2.41633004e-01, -2.26028350e-02, -1.05527180e-01,
         3.16032026e-02, -3.56926513e-01, -1.51980885e-01,
        -2.76101639e-01, -6.73887479e-02, -5.03438625e-02,
        -5.87043804e-02, -2.17410195e-01, -1.90769246e-01,
        -1.66275222e-01,  2.25387182e-02,  4.07006441e-

In [87]:
#подсчет скольких компонент достаточно
k, s, t = 0, 0, 0
while s < 0.9:
    s += variance[t]
    print(s, variance[t])
    t += 1
    k += 1
    
k

0.7389711827152156 0.7389711827152156
0.8490428728139179 0.11007169009870238
0.898993755583708 0.0499508827697901
0.9277429537836405 0.028749198199932456


4

In [88]:
resulting_string = str(k)

file_answer = open("answer.txt", "w")
file_answer.write(resulting_string)
file_answer.close()

Примените построенное преобразование к исходным данным и возьмите значения первой компоненты.

In [37]:
res2 = pca.transform(X_train)
res2

array([[-50.90240358,  17.63167724,   7.7360209 , ...,   3.55657041,
         -5.82197358,  -1.72604005],
       [-52.84690919,  19.14690749,   7.27254551, ...,   3.43259929,
         -5.63318106,  -2.0122316 ],
       [-54.61443917,  19.92735811,   8.10995831, ...,   4.17520282,
         -5.38828678,  -2.75269933],
       ...,
       [ 83.79819948,  16.95241334,  -8.25265611, ...,   2.92390381,
         -4.59543822,  -2.99033503],
       [ 79.19578947,  19.14436008,  -6.93262976, ...,   3.40475421,
         -3.66793327,  -3.57607629],
       [ 82.96885933,  13.13513974,  -9.07644299, ...,   3.75100423,
         -4.79172198,  -3.03918865]])

In [38]:
fcomp = res2[:,0]

Загрузите информацию об индексе Доу-Джонса из файла djia_index.csv. Чему равна корреляция Пирсона между первой компонентой и индексом Доу-Джонса?

In [40]:
dt = pd.read_csv('djia_index.csv')

In [41]:
dt.head()

date          ^DJI
0  2013-09-23  15401.379883
1  2013-09-24  15334.589844
2  2013-09-25  15273.259766
3  2013-09-26  15328.299805
4  2013-09-27  15258.240234

In [49]:
coef = np.corrcoef(fcomp, dt['^DJI'])

In [51]:
ans = round(coef[0,1],2)
ans

0.91

In [52]:
resulting_string = str(ans)

file_answer = open("answer1.txt", "w")
file_answer.write(resulting_string)
file_answer.close()

Какая компания имеет наибольший вес в первой компоненте? Укажите ее название с большой буквы.

In [62]:
first = pd.DataFrame(data=comps[0])
#ищем индекс максимального веса, +1 так как есть еще столбец дат
index_comp = first.idxmax()[0] + 1
index_comp 

27

In [64]:
string = data.columns[index_comp]

In [65]:
resulting_string = string

file_answer = open("answer2.txt", "w")
file_answer.write(resulting_string)
file_answer.close()