In [87]:
import pandas
data = pandas.read_csv('titanic.csv', index_col='PassengerId')

In [88]:
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [89]:
data['Pclass']

PassengerId
1      3
2      1
3      3
4      1
5      3
      ..
887    2
888    1
889    3
890    1
891    3
Name: Pclass, Length: 891, dtype: int64

In [90]:
data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

Ответы:

1.

In [91]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

2.

In [92]:
(data['Survived'] == 1).sum() * 100 // data.shape[0]

38

3.

In [93]:
(data['Pclass'] == 1).sum() * 100 //data.shape[0]

24

4.

In [94]:
data['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [95]:
data['Age'].median()

28.0

In [96]:
data['Age'].mean()

29.69911764705882

5.

In [97]:
data.corr()

Survived    Pclass       Age     SibSp     Parch      Fare
Survived  1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307
Pclass   -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500
Age      -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067
SibSp    -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651
Parch     0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225
Fare      0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000

In [98]:
data.SibSp.corr(data.Parch)

0.4148376986201567

6.

In [99]:
#data.groupby['Sex' == 'female'](data['Name'].value_counts()[:1])

In [100]:
d1 = data.loc[data['Sex'] == 'female']

In [101]:
d1.head()

Survived  Pclass  \
PassengerId                     
2                   1       1   
3                   1       3   
4                   1       1   
9                   1       3   
10                  1       2   

                                                          Name     Sex   Age  \
PassengerId                                                                    
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C

In [102]:
d1['Name'].value_counts()[:1]

Lurette, Miss. Elise    1
Name: Name, dtype: int64

# Важность признаков!

Вот так обучаем дерево:

In [159]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])
clf = DecisionTreeClassifier()
clf.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

Вот так ищем важные признаки:

In [160]:
importances = clf.feature_importances_

Является ли Х пропуском?

In [161]:
np.isnan(X)

array([[False, False],
       [False, False],
       [False, False]])

# ВЫПОЛНЕНИЕ ЗАДАНИЯ

Оставьте в выборке четыре признака: класс пассажира (Pclass), цену билета (Fare), возраст пассажира (Age) и его пол (Sex).

In [162]:
d1 = data[[ 'Pclass', 'Fare', 'Age', 'Sex', 'Survived']]

In [163]:
d1.head()

Pclass     Fare   Age     Sex  Survived
PassengerId                                         
1                 3   7.2500  22.0    male         0
2                 1  71.2833  38.0  female         1
3                 3   7.9250  26.0  female         1
4                 1  53.1000  35.0  female         1
5                 3   8.0500  35.0    male         0

In [164]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 5 columns):
Pclass      891 non-null int64
Fare        891 non-null float64
Age         714 non-null float64
Sex         891 non-null object
Survived    891 non-null int64
dtypes: float64(2), int64(2), object(1)
memory usage: 41.8+ KB


Обратите внимание, что признак Sex имеет строковые значения.

In [165]:
d1 = d1.replace("female", 0).replace("male", 1)

Выделите целевую переменную — она записана в столбце Survived.

In [166]:
d1 = d1.dropna()

In [167]:
d2 = d1[['Survived']]

In [168]:
d1.drop(['Survived'], axis = 1, inplace= True)

In [169]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 1 to 891
Data columns (total 4 columns):
Pclass    714 non-null int64
Fare      714 non-null float64
Age       714 non-null float64
Sex       714 non-null int64
dtypes: float64(2), int64(2)
memory usage: 27.9 KB


In [170]:
d2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 1 to 891
Data columns (total 1 columns):
Survived    714 non-null int64
dtypes: int64(1)
memory usage: 11.2 KB


Обучите решающее дерево с параметром random_state=241 и остальными параметрами по умолчанию (речь идет о параметрах конструктора DecisionTreeСlassifier).

In [171]:
clf = DecisionTreeClassifier(random_state=241)
clf.fit(d1, d2)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=241, splitter='best')

In [172]:
importances = clf.feature_importances_

In [173]:
importances

array([0.14000522, 0.30343647, 0.2560461 , 0.30051221])

In [174]:
print(clf.feature_importances_)

[0.14000522 0.30343647 0.2560461  0.30051221]


In [154]:
import numpy
import pandas
from sklearn.tree import DecisionTreeClassifier


main_data_frame = pandas.DataFrame(data=data, columns=['Pclass', 'Fare', 'Age', 'Sex', 'Survived'])
main_data_frame = main_data_frame[["Pclass", "Fare", "Age", "Sex", "Survived"]].dropna()

filtered_df = main_data_frame[["Pclass", "Fare", "Age", "Sex"]].replace("female", 0).replace("male", 1)

clf = DecisionTreeClassifier(random_state=241)

Y = main_data_frame['Survived']
X = filtered_df
print(X.columns)


clf.fit(X, Y)

print(clf.feature_importances_)

Index(['Pclass', 'Fare', 'Age', 'Sex'], dtype='object')
[0.14000522 0.30343647 0.2560461  0.30051221]
